name: CICD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with maven
        run: mvn clean package
      
      - name: setup docker
        uses: docker/setup-buildx-action@v3
      
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        run: docker build -t jayashreep2005/mycicdapp .
      
      - name: Push to dockerhub
        run: docker push jayashreep2005/mycicdapp:latest